# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Product-Reviews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Product-Reviews
    pod 'SDWebImage'
    pod 'Toast-Swift'
    pod 'ReachabilitySwift'

  target 'Product-ReviewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Product-ReviewsUITests' do
    # Pods for testing
  end

end
